# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    max-connections: 0
    max-http-header-size: 0
    max-http-post-size: 0
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /

#bootweb配置
bootweb:
  version: 1.0.0
  user:
    password:
      # 密码错误{maxRetryCount}次锁定10分钟
      maxRetryCount: 5

spring:
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    servlet:
      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev

# 日志配置
logging:
  level:
    com.jee: debug
    org.springframework: warn


mybatis:
  type-aliases-package: com.jee.boot
  mapper-locations: classpath:mapper/generator/*Mapper.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

